### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by delsonting** [unlessdotcom/gtm-unless-monitor#1]
Template has been approved for the Gallery and should be live in the next day. Once the template is live, consider updating the [documentation](https://unless.com/en/help/technology/google-tag-manager-gtm-monitor/) to get the template from the Template Gallery. This will allow you to take advantage of pushing future updates to your users in Tag Manager and help them migrate to the latest and greatest version.

**Comment by unlessdotcom** [comment]
👍 Updated the documentation.
